spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/mall_db?useSSL=false
        username: root
        password: tmmKing4612.m
    jpa:
        database: mysql
        show-sql: true
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
server:
    port: 10001